GET http://localhost:3000

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json
x-api-key : 0cf1ec8aabfcc4f4a8c2dc84750b4723556f7a04bea58aef40141b199d33c538

{
  "email": "nabil@example.com",
  "password": "SuperSecure123!"
}
